### ISSUE TITLE
Multiple testing and increasing power

### ISSUE THREAD

**Issue by ab08028** [CMPG/polysel#2]
Hello again, 
A few more questions, if you have time! 
1. I've gotten my first set of results running the pipeline :), but there aren't any significant pathways. Are there ways to increase power within the method? I am using nrand=1000000 and 300 repetitions. Since I'm not working with human genes, I started by using all conserved biosystems, subset down following the same criteria you used (>10 of my gene orthologs per pathway, merging those that are 95% similar, etc.). I ended up with 4522 gene sets, which is more than you used in your human-specific biosystems analysis. Could the high number of gene sets make it difficult to have a significant q-value? Or will it not change anything? Should I do some additional filtering of my biosystems?

2. How do you correct for multiple testing across several branches? It's clear how to get the q-values within a branch (e.g. hominidae in the examples), but less clear to me how to deal with the fact that we are testing multiple branches (hominidae, homininae), or in my case, giant otters, sea otters, and the branch leading to them. 

Thank you so much for all your help!
~ Annabel Beichman
Ph.D. Candidate 
Wayne Lab & Lohmueller Lab
EEB, UCLA
annabelbeichman.com

**Comment by jdaub** [comment]
Hi Annabel,

1. I am not sure which filters you used exactly to find the gene sets in Biosystems, but it might be that GO terms are also included. If you search on ‘human[orgn]’ on the Biosystems website, these GO terms are excluded, but from a quick check I see that this is not the case if you choose conserved biosystems.  These GO-sets can be very large (>1000 genes) and I have experienced that such large sets are not suited for our test as they overlap too much with the background. So, what you could try is to take all conserved gene sets of type “pathway” and not having GO as source, or removing all gene sets above a certain size (say 500). This should reduce your collection of gene sets.

2. About the multiple testing: we indeed calculated q-values within a branch and not among all branches. 
We have considered the latter option, as you would think it is statistically more correct to take into account (the p-values from) all tests that we performed within one study. However, the pathways are in each branch tested against a different background, so we were not convinced that they should be pooled together. 
To illustrate: if we take the p-values (before pruning) of all gene sets for all four branches, and recalculate the q-value over all these p-values, for the three most recent branches (homininae, hominidae and hominoidae) the q-values drop considerably compared to the ‘in-branch-q-values’ and as a result we would have 93 instead of 84 significant pathways in these three branches. In contrast, the q-values of the older catarrhini branch increase, and 32 out of the 95 significant sets wouldn’t be significant anymore. I am not sure if this ‘correction’ would give a better representation of the evolutionary history, as for each branch you have a different background to test against, such as the number of gene sets, genes, the power of the branch-site-test that depends on branch length, etc. By pooling p-values, these backgrounds would have an influence on other branches. 
Another (simpler) way to take into account that you are testing over multiple datasets, would be to take a more conservative q-value threshold, say 10% instead of 20%. If we would have applied this threshold we would have lost (before pruning) 73 out of the 179 significant pathways, mainly from the hominidae and catarrhini branches. And after pruning 9 out of the 24 significant sets, again mainly from the hominidae and catarrhini branches. 
But at the end it all comes down to: what is your null hypothesis? In our case, if it would be ‘No gene set has been affected by positive selection in this particular period of time (branch)’, we correct within branch. Instead, if it would have been: ‘No gene set has been affected by positive selection in the four primate branches that lead to humans’ we correct among branches. I think in our case the first hypothesis applies, as we want to know for each branch which gene sets have been under positive selection.

Good luck with the project!
Josephine
